### ISSUE TITLE
Structural git process flow for major package version updates

### ISSUE THREAD

**Issue by MohibWasay** [10pearls/style-guides#28]
Can there be a process to update versions of application dependencies. 

Explanation: In order to update my angular application from version 2 to version 4. Shouldn't there be a process flow in change of version. Branching strategies regarding to the version. If it is a significant change, should this fall into "chore" branch type?

**Comment by umayr** [comment]
There should not be any particular strategy for such framework/library migration. It should be in a separate branch, and then get merged the way other stuff.

Regarding the name, it doesn't matter that much. It could be a feature if your migration adds something to application or if its just for the sake of updating the framework/library, then chore would be suffice. In the end, its just a branch name which would be valueless once it gets merged. So, there's that.
