### ISSUE TITLE
Git: Add guide for commit messages

### ISSUE THREAD

**Issue by mohuk** [10pearls/style-guides#4]
Linked from https://github.com/10pearls/style-guides/pull/1#issuecomment-214992671

You should also add How to structure a commit message in the git style. Commit messages are really important in order to create a useful revision history, teams should first agree on a commit message convention that defines at least the following three things:

Style Markup syntax, wrap margins, grammar, capitalization, punctuation.
Content What kind of information should the body of the commit message (if any) contain? What should it not contain?
Metadata How should issue tracking IDs, pull request numbers, etc. be referenced?
I'd suggest imperative commit messages which has been a thing since the beginning of the git. (Relevant: Link, Link, Link, Link, Link, Link)

To summarize, there are seven rules to draft a sensible commit message:

Separate subject from body with a blank line
Limit the subject line to 50 characters
Capitalize the subject line
Do not end the subject line with a period
Use the imperative mood in the subject line
Wrap the body at 72 characters
Use the body to explain what and why vs. how
An example commit message taken from here:

Summarize changes in around 50 characters or less

More detailed explanatory text, if necessary. Wrap it to about 72
characters or so. In some contexts, the first line is treated as the
subject of the commit and the rest of the text as the body. The
blank line separating the summary from the body is critical (unless
you omit the body entirely); various tools like `log`, `shortlog`
and `rebase` can get confused if you run the two together.

Explain the problem that this commit is solving. Focus on why you
are making this change as opposed to how (the code explains that).
Are there side effects or other unintuitive consequenses of this
change? Here's the place to explain them.

Further paragraphs come after blank lines.
- Bullet points are okay, too
- Typically a hyphen or asterisk is used for the bullet, preceded
  by a single space, with blank lines in between, but conventions
  vary here

If you use an issue tracker, put references to them at the bottom,
like this:

Resolves: #123
See also: #456, #789

**Comment by umayr** [comment]
You could have simply linked it to my comment instead of copy/pasta. :stuck_out_tongue_winking_eye:

**Comment by mohuk** [comment]
@umayr done
